name = "isa2025-api"
compatibility_date = "2024-10-22"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "isa2025-db"
database_id = "beb7b5e5-4196-4a8f-807d-5a5cb56be206"

[observability]
enabled = true
head_sampling_rate = 1
