name = "isa2025-api"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-10-22"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "isa2025-db"
database_id = "beb7b5e5-4196-4a8f-807d-5a5cb56be206"

[[kv_namespaces]]
binding = "KV"
id = "5bfff9b720da468ebce0b001dbbd0b61"

[observability]
enabled = true
head_sampling_rate = 1
